name: "Deploy code to Cloud Function"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/95940715192/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'backend-functions@impactful-shard-374913.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
  deploy:
    needs: authenticate
    name: Deploy
    runs-on: ubuntu-latest 
    steps:
      - run: |
          gcloud functions deploy ScoreReader --runtime dotnet6 --memory 128MB --trigger-topic TransactionScores --region europe-west3 --max-instances 1 --project impactful-shard-374913 --service-account backend-functions@impactful-shard-374913.iam.gserviceaccount.com --allow-unauthenticated --entry-point ScoreReader.ScoreReaderFunction
          
        
