name: "Deploy code to Cloud Function"
on:
  pull_request: {}
  push:
      branches: ["main"]

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'backend-functions@impactful-shard-374913.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'ScoreReader'
        runtime: 'dotnet6'
        entry_point: 'ScoreReader.ScoreReaderFunction'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
